"""add_templates_table

Revision ID: 54b1fdcbedae
Revises: db69f2686c4d
Create Date: 2025-11-08 16:18:28.454073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '54b1fdcbedae'
down_revision: Union[str, None] = 'db69f2686c4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('config_template', sa.JSON(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('use_count', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_templates_category_active', 'templates', ['category', 'is_active'], unique=False)
    op.create_index('idx_templates_created_by_active', 'templates', ['created_by_id', 'is_active'], unique=False)
    op.create_index('idx_templates_public_featured', 'templates', ['is_public', 'is_featured'], unique=False)
    op.create_index('idx_templates_use_count_desc', 'templates', ['use_count'], unique=False)
    op.create_index(op.f('ix_templates_category'), 'templates', ['category'], unique=False)
    op.create_index(op.f('ix_templates_created_by_id'), 'templates', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_templates_id'), 'templates', ['id'], unique=False)
    op.create_index(op.f('ix_templates_is_active'), 'templates', ['is_active'], unique=False)
    op.create_index(op.f('ix_templates_is_featured'), 'templates', ['is_featured'], unique=False)
    op.create_index(op.f('ix_templates_is_public'), 'templates', ['is_public'], unique=False)
    op.create_index(op.f('ix_templates_name'), 'templates', ['name'], unique=True)
    op.create_index(op.f('ix_templates_use_count'), 'templates', ['use_count'], unique=False)
    op.alter_column('subagents', 'priority',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_subagents_parent_agent_id', table_name='subagents')
    op.create_index(op.f('ix_subagents_agent_id'), 'subagents', ['agent_id'], unique=False)
    op.create_index(op.f('ix_subagents_subagent_id'), 'subagents', ['subagent_id'], unique=False)
    op.drop_column('subagents', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subagents', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_subagents_subagent_id'), table_name='subagents')
    op.drop_index(op.f('ix_subagents_agent_id'), table_name='subagents')
    op.create_index('ix_subagents_parent_agent_id', 'subagents', ['agent_id'], unique=False)
    op.alter_column('subagents', 'priority',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.drop_index(op.f('ix_templates_use_count'), table_name='templates')
    op.drop_index(op.f('ix_templates_name'), table_name='templates')
    op.drop_index(op.f('ix_templates_is_public'), table_name='templates')
    op.drop_index(op.f('ix_templates_is_featured'), table_name='templates')
    op.drop_index(op.f('ix_templates_is_active'), table_name='templates')
    op.drop_index(op.f('ix_templates_id'), table_name='templates')
    op.drop_index(op.f('ix_templates_created_by_id'), table_name='templates')
    op.drop_index(op.f('ix_templates_category'), table_name='templates')
    op.drop_index('idx_templates_use_count_desc', table_name='templates')
    op.drop_index('idx_templates_public_featured', table_name='templates')
    op.drop_index('idx_templates_created_by_active', table_name='templates')
    op.drop_index('idx_templates_category_active', table_name='templates')
    op.drop_table('templates')
    # ### end Alembic commands ###
