"""change langchain_tool_ids from ARRAY to JSON for compatibility

Revision ID: 6031ca85c8ae
Revises: e1f2g3h4i5j6
Create Date: 2025-11-10 07:44:55.726734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6031ca85c8ae'
down_revision: Union[str, None] = 'e1f2g3h4i5j6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_backend_config_agent'), 'agent_backend_configs', type_='unique')
    op.create_index(op.f('ix_agent_backend_configs_agent_id'), 'agent_backend_configs', ['agent_id'], unique=True)
    op.create_index(op.f('ix_agent_backend_configs_backend_type'), 'agent_backend_configs', ['backend_type'], unique=False)
    op.create_index(op.f('ix_agent_interrupt_configs_agent_id'), 'agent_interrupt_configs', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_interrupt_configs_tool_name'), 'agent_interrupt_configs', ['tool_name'], unique=False)
    op.create_index(op.f('ix_agent_memory_files_key'), 'agent_memory_files', ['key'], unique=False)
    op.create_index(op.f('ix_agent_memory_files_namespace'), 'agent_memory_files', ['namespace'], unique=False)
    op.create_index(op.f('ix_agent_memory_files_updated_at'), 'agent_memory_files', ['updated_at'], unique=False)
    op.drop_constraint(op.f('uq_memory_namespace_agent'), 'agent_memory_namespaces', type_='unique')
    op.drop_constraint(op.f('uq_memory_namespace_unique'), 'agent_memory_namespaces', type_='unique')
    op.create_index(op.f('ix_agent_memory_namespaces_agent_id'), 'agent_memory_namespaces', ['agent_id'], unique=True)
    op.create_index(op.f('ix_agent_memory_namespaces_namespace'), 'agent_memory_namespaces', ['namespace'], unique=True)
    op.alter_column('agents', 'langchain_tool_ids',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               type_=sa.JSON(),
               existing_nullable=True,
               postgresql_using='array_to_json(langchain_tool_ids)')
    op.create_index('idx_approvals_status', 'execution_approvals', ['status'], unique=False)
    op.create_index(op.f('ix_execution_approvals_execution_id'), 'execution_approvals', ['execution_id'], unique=False)
    op.create_index(op.f('ix_execution_approvals_tool_name'), 'execution_approvals', ['tool_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_execution_approvals_tool_name'), table_name='execution_approvals')
    op.drop_index(op.f('ix_execution_approvals_execution_id'), table_name='execution_approvals')
    op.drop_index('idx_approvals_status', table_name='execution_approvals')
    op.alter_column('agents', 'langchain_tool_ids',
               existing_type=sa.JSON(),
               type_=postgresql.ARRAY(sa.INTEGER()),
               existing_nullable=True,
               postgresql_using='ARRAY(SELECT jsonb_array_elements_text(langchain_tool_ids::jsonb)::integer)')
    op.drop_index(op.f('ix_agent_memory_namespaces_namespace'), table_name='agent_memory_namespaces')
    op.drop_index(op.f('ix_agent_memory_namespaces_agent_id'), table_name='agent_memory_namespaces')
    op.create_unique_constraint(op.f('uq_memory_namespace_unique'), 'agent_memory_namespaces', ['namespace'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_memory_namespace_agent'), 'agent_memory_namespaces', ['agent_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_agent_memory_files_updated_at'), table_name='agent_memory_files')
    op.drop_index(op.f('ix_agent_memory_files_namespace'), table_name='agent_memory_files')
    op.drop_index(op.f('ix_agent_memory_files_key'), table_name='agent_memory_files')
    op.drop_index(op.f('ix_agent_interrupt_configs_tool_name'), table_name='agent_interrupt_configs')
    op.drop_index(op.f('ix_agent_interrupt_configs_agent_id'), table_name='agent_interrupt_configs')
    op.drop_index(op.f('ix_agent_backend_configs_backend_type'), table_name='agent_backend_configs')
    op.drop_index(op.f('ix_agent_backend_configs_agent_id'), table_name='agent_backend_configs')
    op.create_unique_constraint(op.f('uq_backend_config_agent'), 'agent_backend_configs', ['agent_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
